### ISSUE TITLE
nestedEllipsisChange function is never called

### ISSUE THREAD

**Issue by pr0thean** [lentschi/ngx-nested-ellipsis#1]
I am trying to use it like this:

```
HTML
<div
    *nestedEllipsis="true"
    class="postContent"
    [ngClass]="{'cutContent': !contentExpanded}"
    (nestedEllipsisChange)="truncated($event)"
    [innerHTML]="post.content | linkSafeNl2br | emojiToImg"></div>

TS
  truncated(index: number) {
    console.log('post truncated', index);  // this is never called
    this.showShowMore = index !== null;
  }

CSS
  .postContent {
    margin-bottom: 20px;
    overflow-wrap: break-word;
    line-height: 1.35;
  }
  .cutContent {
    max-height: 200px;
  }
```

Div content is cut properly with "..." at the end but truncated function is never called. It works in ngx-ellipsis package though. What am I doing wrong?

**Comment by lentschi** [comment]
The `nestedEllipsisChange` output does work - see this StackBlitz sample:
https://stackblitz.com/edit/ngx-nested-ellipsis-change-output?file=src%2Fapp%2Fapp.component.html
(<- Resize the first box to see the number of characters being changed.)

**Why it's not working for you:**
When using angular's asterisk syntax "sugar" you cannot access the directive's attributes' values in that way. To access an `@Input()` you could write `*nestedEllipsis="true; indicator"`, but there still is no way to do the same for an `@Output()` such as `nestedEllipsisChange` (see [open angular bug](https://github.com/angular/angular/issues/12121))

So to fix your problem, you'll need to use something like this (I just inline edited your above code - this is untested!):

```html
<div class="postContent" [class.cutContent]="!contentExpanded">
  <ng-template nestedEllipsis (nestedEllipsisChange)="truncated($event)">
     <span [innerHTML]="post.content | linkSafeNl2br | emojiToImg"></span>
  <ng-template>
</div>
```

**Comment by pr0thean** [comment]
Thank you for explanation but I still had problems with innerHTML and pipes with this solution. I decided to use other package because it suited better to my structure.
