### ISSUE TITLE
I got an error after updating my project to angular 15 

### ISSUE THREAD

**Issue by cfgi-lul** [lentschi/ngx-nested-ellipsis#21]
I use angular 15.0.2
cdk 15.0.1
node 16.18.x
and got an error while I deploy my app.
#12 5.611 npm ERR! code ERESOLVE
#12 5.615 npm ERR! ERESOLVE could not resolve
#12 5.615 npm ERR! 
#12 5.615 npm ERR! While resolving: ngx-nested-ellipsis@2.1.0
#12 5.616 npm ERR! Found: @angular/common@15.0.2

**Comment by lentschi** [comment]
@cfgi-lul Fixed in `ngx-nested-ellipsis@2.1.1`. (It was just a peer dependency issue - there's no real changes to 2.1.0)
