### ISSUE TITLE
Dependency Angular 16

### ISSUE THREAD

**Issue by corentinchevret** [lentschi/ngx-nested-ellipsis#28]
Would it be possible to add Angular 16 version in dependency for `npm install` please ?

![image](https://github.com/lentschi/ngx-nested-ellipsis/assets/16131970/82185553-f1a0-45e5-8a0c-99d5983e863d)

I tested with `npm install --force` and I didn't have any problem :)

Thanks !

**Comment by lentschi** [comment]
@corentinchevret Thanks for pointing that out - it's done in `ngx-nested-ellipsis@2.1.3`
