### ISSUE TITLE
Library not working in ie 11

### ISSUE THREAD

**Issue by Devyani20** [lentschi/ngx-nested-ellipsis#4]
The issue is that the library is not working in ie11 and giving this error
![image](https://user-images.githubusercontent.com/57898970/114843188-32d16a00-9df7-11eb-93cb-5257164b2695.png)

This is because of this .browserslistrc file as it excludes the ie11 version
Can you provide a way to make it work in ie 11 also

**Comment by lentschi** [comment]
Fixed in `ngx-nested-ellipsis@1.1.3`- However I'll stop supporting IE as soon as angular 13 is stable as it will no longer be supported by the framework then - see: https://angular.io/guide/deprecations#internet-explorer-11
